Repository memgraph/orb, pull requests merged in 2022-09, with the labels that each got.

#10 Fix: Handle the initial container size for renderer
  src/views/default-view.ts
  src/views/map-view.ts
Labels: bug

#8 Chore: Add DefaultView docs, update examples with small explanation
  README.md
  docs/assets/view-default-fixed.png
  docs/assets/view-default-simulated.png
  docs/view-default.md
  examples/example-1.html
  examples/example-2.html
  examples/example-3.html
  examples/example-4.html
  examples/example-5.html
  examples/example-6.html
Labels: documentation

#9 Chore: Fix documentation, build and release process
  .eslintignore
  .github/CODEOWNERS
  .github/workflows/build.yml
  .github/workflows/release.yml
  CONTRIBUTING.md
  README.md
  docs/assets/graph-example.png
  docs/styles.md
  examples/example-4.html
  examples/index.html
  examples/simulator-scenarios.html
  package.json
  src/orb.ts
  src/views/shared.ts
  webpack.config.js
Labels: documentation

#13 Chore: Fix docs and general orb API issues
  README.md
  docs/assets/logo.png
  docs/data.md
  docs/events.md
  docs/styles.md
  docs/view-default.md
  docs/view-map.md
  examples/example-custom-styled-graph.html
  examples/example-fixed-coordinates-graph.html
  examples/example-graph-data-changes.html
  examples/example-graph-events.html
  examples/example-graph-on-map.html
  examples/example-simple-graph.html
  examples/index.html
  examples/playground.html
  src/index.ts
  src/models/edge.ts
  src/models/graph.ts
  src/models/node.ts
  src/models/strategy.ts
  src/models/style.ts
  src/orb.ts
  src/renderer/canvas/edge/base.ts
  src/renderer/canvas/edge/types/edge-curved.ts
  src/renderer/canvas/edge/types/edge-loopback.ts
  src/renderer/canvas/edge/types/edge-straight.ts
  src/renderer/canvas/node.ts
  test/models/graph.spec.ts
Labels: bug, documentation, enhancement

#14 Fix: Fix image loading on node style properties
  src/models/graph.ts
  src/models/node.ts
Labels: bug

#11 Chore: Add pre commit hook
  .commitlintrc.json
  .husky/commit-msg
  .releaserc
  package-lock.json
  package.json
Labels: documentation
